[package]
name = "mechantmechant"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.7"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }