[package]
name = "mechantmechant"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
clipboard-win = "4.0"
windows-service = "0.5"